services:
    postgres:
        image: postgres:15
        container_name: laravel_postgres
        environment:
            POSTGRES_DB: laravel_db
            POSTGRES_USER: laravel_user
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - laravel_network

    app:
        build: .
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        networks:
            - laravel_network
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    laravel_network:
        driver: bridge

volumes:
    postgres_data:
