version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: laravel_postgres
        environment:
            POSTGRES_DB: laravel_db
            POSTGRES_USER: laravel_user
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - laravel_network

    # Se você quiser adicionar o Laravel no mesmo compose (opcional)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        networks:
            - laravel_network

volumes:
    postgres_data:

networks:
    laravel_network:
        driver: bridge
